name: Test Workflows
on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Which test to run'
        required: true
        type: choice
        options:
          - whatsapp-only
          - secrets-verification
          - docker-build
          - all

jobs:
  # Test WhatsApp Notification
  test-whatsapp:
    if: github.event.inputs.test_type == 'whatsapp-only' || github.event.inputs.test_type == 'all'
    uses: ./.github/workflows/whatsapp-notification.yml
    with:
      message: "🧪 Test message from GitHub Actions\nRepository: ${{ github.repository }}\nTriggered by: ${{ github.actor }}"
      phone: ${{ secrets.WHATSAPP_GROUP_ID }}
      host: ${{ secrets.WHATSAPP_API_HOST }}
    secrets:
      basic_auth: ${{ secrets.WHATSAPP_BASIC_AUTH }}

  # Test Secret Configurations
  test-secrets:
    if: github.event.inputs.test_type == 'secrets-verification' || github.event.inputs.test_type == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Check Required Secrets
        run: |
          missing_secrets=()
          
          # Docker Hub Secrets
          [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ] || missing_secrets+=("DOCKERHUB_USERNAME")
          [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ] || missing_secrets+=("DOCKERHUB_TOKEN")
          
          # Easypanel Secrets
          [ -n "${{ secrets.EASYPANEL_API_URL }}" ] || missing_secrets+=("EASYPANEL_API_URL")
          [ -n "${{ secrets.EASYPANEL_API_KEY }}" ] || missing_secrets+=("EASYPANEL_API_KEY")
          [ -n "${{ secrets.EASYPANEL_PROJECT_ID }}" ] || missing_secrets+=("EASYPANEL_PROJECT_ID")
          [ -n "${{ secrets.EASYPANEL_SERVICE_NAME }}" ] || missing_secrets+=("EASYPANEL_SERVICE_NAME")
          
          # WhatsApp Secrets
          [ -n "${{ secrets.WHATSAPP_GROUP_ID }}" ] || missing_secrets+=("WHATSAPP_GROUP_ID")
          [ -n "${{ secrets.WHATSAPP_API_HOST }}" ] || missing_secrets+=("WHATSAPP_API_HOST")
          [ -n "${{ secrets.WHATSAPP_BASIC_AUTH }}" ] || missing_secrets+=("WHATSAPP_BASIC_AUTH")
          
          if [ ${#missing_secrets[@]} -ne 0 ]; then
            echo "❌ Missing required secrets:"
            printf '%s\n' "${missing_secrets[@]}"
            exit 1
          else
            echo "✅ All required secrets are configured"
          fi

      - name: Validate Easypanel API
        if: success()
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.EASYPANEL_API_URL }}/api/v1/projects
          method: 'GET'
          bearerToken: ${{ secrets.EASYPANEL_API_KEY }}
          preventFailureOnNoResponse: true

      - name: Send Success Notification
        if: success()
        uses: ./.github/workflows/whatsapp-notification.yml
        with:
          message: "✅ All secrets and API connections verified successfully!"
          phone: ${{ secrets.WHATSAPP_GROUP_ID }}
          host: ${{ secrets.WHATSAPP_API_HOST }}
        secrets:
          basic_auth: ${{ secrets.WHATSAPP_BASIC_AUTH }}

  # Test Docker Build
  test-docker:
    if: github.event.inputs.test_type == 'docker-build' || github.event.inputs.test_type == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test Docker Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:test
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:buildcache

      - name: Send Success Notification
        if: success()
        uses: ./.github/workflows/whatsapp-notification.yml
        with:
          message: "✅ Docker build test completed successfully!"
          phone: ${{ secrets.WHATSAPP_GROUP_ID }}
          host: ${{ secrets.WHATSAPP_API_HOST }}
        secrets:
          basic_auth: ${{ secrets.WHATSAPP_BASIC_AUTH }}
